### ISSUE TITLE
Commands don't work on 0.7.1.9

### ISSUE THREAD

**Issue by JhettHeliks** [Khanx/AdvancedWand#26]
I don't know if this was made to work with the version 0.7.1.9. But I am able to select the area i wish to edit but it keeps saying that the wand is not on, I used the command //wand to get the wand,, and I did get the wand. So I uninstalled it and reinstalled it and now it says the //copy command does not exist.

**Comment by Khanx** [comment]
The mod works with the 0.7.1.9 version (just tested)

I think that your problem is that you don't have permissions to use the wand

You have several options:

a) Modify the permission file and add "khanx.wand"
b) Use /cheats on
